version: '3'
services:
  elastic:
    image: "elasticsearch:7.6.1"
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/local/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 1G
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - cluster.name=docker-cluster
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    cap_add:
      - IPC_LOCK
    networks:
      - esnet
  kibana:
    image: "kibana:7.6.1"
    container_name: kibana
    networks:
      - esnet
    ports:
      - "5601:5601"

networks:
  esnet:
    driver: bridge

volumes:
  esdata:
    driver: local
